name: Update GitHub Readme Stats

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Generate stats card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: include_all_commits=false&show_icons=true&theme=github_dark_dimmed&disable_animations=true
          path: stats/stats.svg
          token: ${{ secrets.PAT_1 }}

      - name: Generate top languages card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=xujiayao&theme=github_dark_dimmed&layout=pie&disable_animations=true
          path: stats/top-langs.svg
          token: ${{ secrets.PAT_1 }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add stats/*.svg
          git commit -m "Update Update GitHub Readme Stats" || exit 0
          git push
